import axios from "axios";
import Navbar from "components/Navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Typography, Card, Carousel } from "antd";
import React from "react";
import { Article } from ".";

const { Text } = Typography;

const { Meta } = Card;

const Show = () => {
  const router = useRouter();
  const { slug } = router.query;
  const [article, setArticle] = useState<{
    id: string;
    type: string;
    attributes: Article;
  }>({
    id: "",
    type: "",
    attributes: {
      created_at: "",
      description: "",
      images: [""],
      slug: "",
      title: "",
      visible: false,
    },
  });

  const [count, setCount] = useState(1);
  useEffect(() => {
    if (count <= 1) {
      axios
        .get(`http://localhost:3000/articles/${slug}`)
        .then((val) => setArticle(val.data.data));
      setCount(count + 1);
    }
  }, [count, setCount, slug]);

  const { attributes } = article;
  useEffect(() => {
    const intervalId = setInterval(() => {
      axios
        .get(`http://localhost:3000/articles/${slug}`)
        .then((val) => setArticle(val.data.data));
    }, 30000);

    return () => clearInterval(intervalId); //This is important
  }, [setArticle, article, slug]);
  return (
    <div>
      <Head>
        <title>Article</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div>
        <Card style={{ width: 500 }}>
          <Carousel>
            {attributes.images.map((image) => (
              <div key={image}>
                <img src={image} width={400} alt='' />
              </div>
            ))}
          </Carousel>
          <br></br>
          <Meta title={attributes.title} description={attributes.description} />
          <br></br>
          <Text underline>
            {new Date(attributes.created_at).toDateString()}
          </Text>
        </Card>
      </div>
    </div>
  );
};

export default Show;
